name: apec
on:
  schedule:
    - cron: '1 1,10 * * *'
env:
  abtc_application_number: ${{ secrets.ABTC_APPLICATION_NUMBER }}
  gmail_password: ${{ secrets.GMAIL_PASSWORD }}
  gmail_id : ${{ vars.GMAIL_ID }}
  to_email_ids: ${{ secrets.TO_EMAIL_IDS }}

jobs:
  check-apec-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip selenium requests wheel
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: python3 main.py
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "[AUTO] Updated countries list"
      